In [1]:
import numpy as np

arr = np.arange(0, 50, 5)

In [2]:
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [4]:
arr[0]

0

In [5]:
arr[-1]

45

In [6]:
arr [:]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [7]:
arr[:4]

array([ 0,  5, 10, 15])

In [8]:
arr[1:-1] = 50

In [9]:
arr

array([ 0, 50, 50, 50, 50, 50, 50, 50, 50, 45])