In [2]:
import numpy as np


arr_1 = np.array([1,2,3,4])
arr_2 = np.array([6,7,8,9])

arr_1 + arr_2

array([ 7,  9, 11, 13])

In [3]:
arr_1-arr_1

array([0, 0, 0, 0])

In [4]:
arr_1 - arr_2 

array([-5, -5, -5, -5])

In [5]:
arr_1 * arr_2 

array([ 6, 14, 24, 36])

In [6]:
arr_1 * 10

array([10, 20, 30, 40])

In [7]:
arr_1 / arr_2

array([0.16666667, 0.28571429, 0.375     , 0.44444444])

In [8]:
arr_1 / 2 

array([0.5, 1. , 1.5, 2. ])

In [9]:
arr_1 ** arr_2

array([     1,    128,   6561, 262144])

In [15]:
arr_5 = np.array([[1, 2], [3, 4]])
arr_6 = np.array([[5,6], [7,8]])  

arr_5 + arr_6

array([[ 6,  8],
       [10, 12]])

In [16]:
arr_5 * 3

array([[ 3,  6],
       [ 9, 12]])